[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
  olikraus/U8g2@^2.36.6
  adafruit/Adafruit NeoPixel@^1.12.3
  adafruit/Adafruit BME680 Library@^2.0.4
  claws/BH1750@^1.3.0
  waspinator/AccelStepper@^1.64
